config/routes.rb
Rails.application.routes.draw do
  root 'page#home'
  get '/home',to:'page#home'
  resources :recipes do 
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new]
  get '/register',to: 'chefs#new'
  get '/login',to: 'logins#new'
  post '/login',to: 'logins#create'
  get '/logout',to: 'logins#destroy'
  
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 3,maximum: 50}
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum:50}, uniqueness: {case_sensitive: false},
                                             format: { with: VALID_EMAIL_REGEX}
   has_secure_password                                         
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe
  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes
  has_many :recipe_styles
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  validates :chef_id, presence: true
  validates :name, presence: true,length:{minimum:3,maximum:50}
  validates :summary, presence: true,length:{minimum:5,maximum:150}
  validates :decsription, presence: true,length:{minimum:5,maximum:500}
  mount_uploader :picture, PictureUploader
  validate :picture_size
  default_scope -> {order(updated_at: :desc)}
  def thumbs_up_total
    self.likes.where(like: true).size
  end
  def thumbs_down_total
    self.likes.where(like: false).size
  end
  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture,"should be less than 5mb")
      end
    end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_style.rb
class RecipeStyle < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id] 
  end
  def logged_in?
    !!current_user
  end
  def require_user
    if !logged_in?
      flash[:danger]="you must be logged in to perform this action"
      redirect_to root_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :find_chef, only: [:edit,:update,:show]
  
  before_action :require_same_user, only: [:edit,:update]
  def index
    @chefs=Chef.paginate(page: params[:page],per_page: 2)
  end
  def new
    @chef=Chef.new
  end
  def create
    @chef=Chef.new(chef_params)
    if @chef.save
      flash[:success]="Action Completed Successfully"
      redirect_to recipes_path
    else
      render 'new'
    end
  end
  def edit
  end
  def update
    if @chef.update(chef_params)
      flash[:success]="Your profile has been updated"
      redirect_to chef_path(@chef)
    else
      render 'edit'
    end
  end
  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 2)
  end
  def find_chef
    @chef=Chef.find(params[:id])
  end
  private 
   def chef_params
     params.require(:chef).permit(:name, :email, :password)
   end
   def require_same_user
     if current_user != @chef
       flash[:danger]="You can only edit your own profile"
       redirect_to root_path
     end
   end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    
  end
  def create
    chef=Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id]=chef.id
      flash[:success]="You are Logged in"
      redirect_to recipes_path
    else
      flash.now[:danger]="your Email/Password does not match"
      render 'new'
    end
  end
  def destroy
    session[:chef_id]=nil
    flash[:success]="You have logged out successfully"
    redirect_to root_path
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show,:edit,:update,:destroy,:like]
  before_action :require_same_user, only: [:edit,:update]
  before_action :require_user, except: [:show,:index]
  after_action :confirm_msg, only: [:create,:update,:destroy]
  def index
    @recipes=Recipe.paginate(page: params[:page],per_page: 2)
    #@recipes=Recipe.all.sort_by{|likes| likes.thumbs_up_total}.reverse ---for recipes based on no of likes
    #@recipes=Recipe.all.order("created_at DESC") ----for recipes based on created time
  end
  
  def show
    
  end
  
  def new
    @recipe=Recipe.new
  end
  
  def create
    @recipe=Recipe.new(recipe_params)
    @recipe.chef=current_user
    
    if @recipe.save
      redirect_to recipes_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end
  
  def find_recipe
    @recipe=Recipe.find(params[:id])
  end
  
  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end
  
  def confirm_msg
    flash[:success]="Action completed successfully"
  end 
  
  def like
    like=Like.create(like: params[:like],chef: current_user,recipe: @recipe)
      if like.valid?
        flash[:success]="Action Completed Successfully"
        redirect_to :back
      else
        flash[:danger]="You can only like/dislike only once"
        redirect_to :back
      end
  end
  
  private
    def recipe_params
      params.require(:recipe).permit(:name,:summary,:decsription,:picture)
    end
    def require_same_user
     if current_user != @recipe.chef
       flash[:danger]="You can only edit your own profile"
       redirect_to root_path
     end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef,options={size:80})
    gravatar_id=Digest::MD5::hexdigest(chef.email.downcase)
    size=options[:size]
    gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: chef.name,class: "gravatar")
  end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors',obj: @chef %>
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
     <%= form_for @chef do |i| %>
       <%= i.label :name %>
       <%= i.text_field :name %>
       <%= i.label :email %>
       <%= i.email_field :email %>
       <%= i.label :password %>
       <%= i.password_field :password %>
       <span class="pic">
         <%= i.file_field :picture, accept: 'image/jpeg,image/png,image/gif' %>
       </span>
       <%= i.submit(@chef.new_record? ? "Register": "Edit Profile",class:"btn btn-success") %>
       <% end %>
 </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title',title: "Edit Your Profile" %>
<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title',title: "Our Chefs" %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to "Chefs",chefs_path %>
  </li>
  <li>
    <%= link_to "Recipes",recipes_path %>
  </li>
</ul>
  <div class="col-md-4 col-md-offset-4 center">
      <%= will_paginate @chef %>
  </div>

  <% @chefs.each do |chef| %>
      <div class="row">
        <div class="col-md-4 col-md-offset-4 center">
          <section class="chef_know_how">
            <%= link_to (gravatar_for chef,size:100),chef_path(chef) %>
            <h5>Chef name:<%= chef.name %></h5>
          </section>
        </div>
      </div>
  <% end %>
  

app/views/chefs/new.html.erb
<%= render 'shared/page_title',title: "Register Your Account" %>
<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title',title: "Chefname:"+ @chef.name %>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for @chef,size:200 %>
      <hr>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3><em>Recipes:</em></h3>
    <%= will_paginate @recipes %>
  </div>
</div>

<% @chef.recipes.each do |recipe| %>
  <div class="row">
    <div class="col-lg-6 well col-lg-offset-3">
      <h3><%= link_to recipe.name,recipe_path(recipe) %></h3>
      <%= link_to "View Recipe",recipe_path(recipe),class:"btn btn-warning btn-small pull-right" %>
      <p>
        <%= recipe.summary%>
      </p>
      <p>
        <span class="quiet"><small>Created: <%= time_ago_in_words(recipe.created_at)%> ago <br/></small></span>
        <span class="quiet"><small>Updated: <%= time_ago_in_words(recipe.updated_at)%> ago </small></span>
      </p>
      <div class="pull-right">
          <%= link_to like_recipe_path(recipe,like: true), method: :post do %>
          <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp<%= recipe.thumbs_up_total %>
          <% end %>&nbsp&nbsp&nbsp&nbsp
          <%= link_to like_recipe_path(recipe,like: false), method: :post  do %>
          <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp<%= recipe.thumbs_down_total %>
          <% end %>
        </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy;MyRecipes2015</p>
    </div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |key,value| %>
    <div class="alert alert-<%= key %>"><%= value %>
    <a class="close" data-dismiss="alert">&#215;</a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "Recipes",root_path,class:"btn btn-lg btn-success",id:"logo"%>
    <div class="nav_item">
      <%= link_to "link1","",class:"btn btn-sm btn-Default btn-warning",id:"link1"%>
    </div>
    <div class="nav_item">
      <%= link_to "Register",register_path,class:"btn btn-sm btn-default btn-warning",id:"link1"%>
    </div>
    <% if logged_in? %>
      <ul class="nav_item pull-right">
        <li class="dropdown">
          <%= link_to "#",class:"btn btn-lg btn-info dropdown-toggle","data-toggle"=>"dropdown" do %>
            <%= current_user.name %> <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "My Recipes",chef_path(current_user) %></li>
            <li><%= link_to "Create Recipe",new_recipe_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Edit Profile",edit_chef_path(current_user) %></li>
            <li><%= link_to "Log out",logout_path %></li>
          </ul>
        </li>
      </ul>
    <% else %>
      <div class="nav_item">
        <%= link_to "Log in",login_path,class:"btn btn-sm btn-info",id:"link1"%>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </div>

</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title',title: "Log in" %>


<div class="row">
 <div class="well col-md-6 col-md-offset-3">
  <%= form_tag '/login' do %>
   <%= label_tag :email %>
   <%= text_field_tag :email %>
   <%= label_tag :password %>
   <%= password_field_tag :password %>
   <%= submit_tag 'Login',class: "btn btn-success" %>
  <% end %>
 </div>
</div>

app/views/page/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to My Recipes Blog</h1>
  <h2>To share my taste buds favourites at one place.</h2>
  <%= link_to "Sign Up now!",register_path,class:"btn btn-lg btn-success"%>
</div>
<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipe Listings
    </h3>
    <h2 class="left">Browse and View Recipes as a guest and sign up later.</h2>
    <p><%= link_to "Browse Recipe Listings",recipes_path,class:"btn btn-sm btn-warning"%></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Log in
    </h3>
    <h2 class="left">Add/update recipes,create reviews/like-dislike recipes and many more</h2>
    <p><%= link_to "Log in to your Account",login_path,class:"btn btn-sm btn-warning"%></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipe Listings
    </h3>
    <h2 class="left"> Browse and View Recipes as a guest and sign up later.</h2>
    <p><%= link_to "Browse Recipe Listings","",class:"btn btn-sm btn-warning"%></p>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors',obj: @recipe %>
<div class="row">
  <div class="well col-md-8 col-md-offset-2">
     <%= form_for(@recipe, html: { multipart: true }) do |i| %>
       <%= i.label :name %>
       <%= i.text_field :name %>
       <%= i.label :summary %>
       <%= i.text_field :summary %>
       <%= i.label :decsription %>
       <%= i.text_area :decsription,rows: 10 %>
       <span class="pic">
         <%= i.file_field :picture, accept: 'image/jpeg,image/png,image/gif' %>
       </span>
       <%= i.submit(@recipe.new_record? ? "Create Recipe": "Update Recipe",class:"btn btn-success") %>
       <% end %>
 </div>
</div>
<script type="text/javascript">
 $('#recipe_picture').bind('change',function() {
  var size_in_megabytes = this.files[0].size/1024/1024;
  if (size_in_megabytes > 5) {
    alert("Max file size is 5MB.Please upload small pic");
  }
});
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe Section" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title',title: "All Recipes" %>
<ul class="nav nav-tabs">
  <li>
    <%= link_to "Chefs",chefs_path %>
  </li>
  <li class="active">
    <%= link_to "Recipes",recipes_path %>
  </li>
</ul><br/>
<% @recipes.each do |recipe| %>
<div class="row">
  <div class="col-md-2">
    <section class="chef_know_how">
      <%= link_to gravatar_for(recipe.chef,size:100),chef_path(recipe.chef) %>
      <h5>Chef name:<%= recipe.chef.name %></h5>
    </section>
  </div>
  <div class="col-lg-6 well">
    <h3><%= link_to recipe.name,recipe_path(recipe) %></h3>
    <%= link_to "View Recipe",recipe_path(recipe),class:"btn btn-warning btn-small pull-right" %>
    <p>
      <%= recipe.summary%>
    </p>
    <p>
      <span class="quiet"><small>Created: <%= time_ago_in_words(recipe.created_at)%> ago <br/></small></span>
      <span class="quiet"><small>Updated: <%= time_ago_in_words(recipe.updated_at)%> ago </small></span>
    </p>
    <div class="pull-right">
        <%= link_to like_recipe_path(recipe,like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp<%= recipe.thumbs_up_total %>
        <% end %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(recipe,like: false), method: :post  do %>
        <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp<%= recipe.thumbs_down_total %>
        <% end %>
      </div>
  </div>
  <div class="col-md-4">
    <%= image_tag(recipe.picture.url, size:"250*150",class: "gravatar") if recipe.picture? %>
  </div>
</div>
<hr>
<% end %>
<%= will_paginate @recipes %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title',title: "Make Recipe Section" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title',title: @recipe.name %>
<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to (gravatar_for @recipe.chef,size: 200),chef_path(@recipe.chef) %>
    <p><h3>Recipe by:<%=@recipe.chef.name %></h3></p>
  </div>
  <div class="col-md-8">
    <% if logged_in? and @recipe.chef===current_user %>
      <%= link_to "Delete Recipe",recipe_path(@recipe),class:"btn btn-danger pull-right",method: :delete,data: {confirm: "Are You sure?"} %>
      <%= link_to "Edit Recipe",edit_recipe_path(@recipe),class:"btn btn-success pull-right" %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    </div>
    <div class="well">
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.decsription) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe,like: true), method: :post do %>
        <i class="glyphicon glyphicon-thumbs-up"></i>&nbsp<%= @recipe.thumbs_up_total %>
        <% end %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe,like: false), method: :post  do %>
        <i class="glyphicon glyphicon-thumbs-down"></i>&nbsp<%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<h5><%=link_to "Return to Recipes",recipes_path,class:"btn btn-warning btn-small" %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="alert alert-danger col-md-8 col-md-offset-2">
    <h3><strong>Please correct the following errors</strong></h3>
    <ul>
    <% obj.errors.full_messages.each do |i| %>
    <li><%= i %></li>
    <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><strong><%= title %></strong></h1>
  <hr>
</p>